---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending
filter-by-commitish: true
categories:
  - title: ":boom: Breaking changes"
    label: "pr: Breaking Change"

  - title: ":sparkles: New features"
    label: "pr: new-feature"

  - title: ":zap: Enhancements"
    label: "pr: enhancement"

  - title: ":recycle: Refactor"
    label: "pr: refactor"

  - title: ":bug: Bug Fixes"
    label: "pr: bugfix"

  - title: ":arrow_up: Dependency Updates"
    labels:
      - "pr: dependency-update"
      - "dependencies"

include-labels:
  - "pr: Breaking Change"
  - "pr: enhancement"
  - "pr: dependency-update"
  - "pr: new-feature"
  - "pr: bugfix"
  - "pr: refactor"

version-resolver:
  major:
    labels:
      - "pr: Breaking Change"
  minor:
    labels:
      - "pr: enhancement"
      - "pr: dependency-update"
      - "pr: new-feature"
  patch:
    labels:
      - "pr: bugfix"
  default: patch

template: |
  $CHANGES
