---
name: Release Drafter

on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v*"
  workflow_dispatch:

permissions: read-all

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # https://github.com/release-drafter/release-drafter
      - uses: release-drafter/release-drafter@67e173cadb2fbd3de94f4a861e0c48c913b462ae # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
