 version: 2

 build:
   os: "ubuntu-24.04"
   tools:
     python: "3.13"
   jobs:
     pre_install:
       - pip install --upgrade pip
       - pip install --group docs

 mkdocs:
   configuration: mkdocs.rtd.yml
