site_name: ""
site_description: "Automatic documentation from sources, for MkDocs."
site_url: http://github.com
repo_url: https://github.com/Yakifo/amqtt
repo_name: Yakifo/amqtt
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, docs, amqtt]
copyright: TBD
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home:
      - Overview: index.md
      - Quickstart: quickstart.md
      - CLI Usage:
          - Broker: references/amqtt.md
          - Publisher: references/amqtt_pub.md
          - Subscriber: references/amqtt_sub.md
      - API Usage:
          - Broker: references/broker.md
          - Client: references/client.md
      - Plugins:
          - $SYS: plugins/sys_broker.md
      - Reference:
          - Contributing: contributing.md
          - Code of Conduct: code_of_conduct.md
          - Security: security.md
          - License: license.md
#  - Changelog: changelog.md
#  - Credits: credits.md
#  - License: license.md
#- Usage:
#  - usage/index.md
#  - Theming: usage/theming.md
#  - Handlers: usage/handlers.md
#  - All handlers:
#    - C: https://mkdocstrings.github.io/c/
#    - Crystal: https://mkdocstrings.github.io/crystal/
#    - Python: https://mkdocstrings.github.io/python/
#    - Python (Legacy): https://mkdocstrings.github.io/python-legacy/
#    - Shell: https://mkdocstrings.github.io/shell/
#    - TypeScript: https://mkdocstrings.github.io/typescript/
#    - VBA: https://pypi.org/project/mkdocstrings-vba
#  - Guides:
#    - Recipes: recipes.md
#    - Troubleshooting: troubleshooting.md
#- API reference: reference/mkdocstrings.md
#- Development:
#  - Contributing: contributing.md
#  - Code of Conduct: code_of_conduct.md
#  - Coverage report: coverage.md
#- Insiders:
#  - insiders/index.md
#  - Getting started:
#    - Installation: insiders/installation.md
#    - Changelog: insiders/changelog.md
#- Author's website: https://pawamoy.github.io/

theme:
  name: material
  logo: assets/amqtt_bw.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.instant.preview
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/extra.css
#- css/style.css
#- css/material.css
#- css/mkdocstrings.css
#- css/insiders.css

#extra_javascript:
#- js/feedback.js

markdown_extensions:
  - attr_list
  - admonition
  - callouts:
      strip_period: false
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: !relative $config_dir
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "¤"

plugins:
  - search
  - autorefs
  - markdown-exec
  - section-index
  - coverage
  - mkdocstrings:
      handlers:
        python:
          #        inventories:
          #        - https://docs.python.org/3/objects.inv
          #        - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
          #        - https://mkdocstrings.github.io/autorefs/objects.inv
          #        - https://www.mkdocs.org/objects.inv
          #        - https://python-markdown.github.io/objects.inv
          #        - https://jinja.palletsprojects.com/en/stable/objects.inv
          #        - https://markupsafe.palletsprojects.com/en/stable/objects.inv
          paths: [amqtt]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
  #- llmstxt:
  #    files:
  #    - output: llms-full.txt
  #      inputs:
  #      - index.md
  #      - usage/index.md
  #      - usage/handlers.md
  #      - usage/theming.md
  #      - recipes.md
  #      - troubleshooting.md
  #      - reference/**.md
  - git-revision-date-localized:
      enabled: !ENV [DEPLOY, false]
      enable_creation_date: true
      type: timeago
  #- redirects:
  #    redirect_maps:
  #      theming.md: usage/theming.md
  #      handlers/overview.md: usage/handlers.md
  #      reference/index.md: reference/mkdocstrings.md#mkdocstrings
  #      reference/extension.md: reference/mkdocstrings.md#mkdocstrings.extension
  #      reference/handlers/index.md: reference/mkdocstrings.md#mkdocstrings.handlers
  #      reference/handlers/base.md: reference/mkdocstrings.md#mkdocstrings.handlers.base
  #      reference/handlers/rendering.md: reference/mkdocstrings.md#mkdocstrings.handlers.rendering
  #      reference/inventory.md: reference/mkdocstrings.md#mkdocstrings.inventory
  #      reference/loggers.md: reference/mkdocstrings.md#mkdocstrings.loggers
  #      reference/plugin.md: reference/mkdocstrings.md#mkdocstrings.plugin
  - minify:
      minify_html: !ENV [DEPLOY, false]
  - group:
      enabled: !ENV [MATERIAL_INSIDERS, false]
      plugins:
        - typeset

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pawamoy
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@pawamoy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pawamoy
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/mkdocstrings/community
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocstrings/
#  analytics:
#    feedback:
#      title: Was this page helpful?
#      ratings:
#        - icon: material/emoticon-happy-outline
#          name: This page was helpful
#          data: 1
#          note: Thanks for your feedback!
#        - icon: material/emoticon-sad-outline
#          name: This page could be improved
#          data: 0
#          note: Let us know how we can improve this page.
