services:
  amqtt:
    image: amqtt
    container_name: amqtt
    ports:
      - "1884:1884"
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./broker.yaml:/app/conf/broker.yaml
