services:
  amqtt:
    image: amqtt/amqtt
    container_name: amqtt
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8g
        reservations:
          cpus: '3'
          memory: 8g
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8443:8443"
      - "8883:8883"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./broker.yaml:/app/conf/broker.yaml
      - /etc/letsencrypt:/app/cert:ro
