---
name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

env:
  UV_CACHE_DIR: /tmp/.uv-cache
  PROJECT_PATH: "amqtt"

permissions:
  contents: read

jobs:
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: ⤵️ Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      # https://github.com/astral-sh/setup-uv
      - name: 🏗 Install uv and Python
        uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff # v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          cache-local-path: ${{ env.UV_CACHE_DIR }}
          python-version: "3.13"

      - name: install openldap dependencies
        run: sudo apt-get install -y libldap2-dev libsasl2-dev

      - name: 🏗 Install the project
        run: uv sync --locked --dev --all-extras

      - name: Run secret scan
        run: uv run --frozen pre-commit run gitleaks-full --hook-stage manual

      - name: Run mypy
        run: uv run --frozen mypy ${{ env.PROJECT_PATH }}/
      - name: Pylint review
        run: uv run --frozen pylint ${{ env.PROJECT_PATH }}/
      - name: Ruff check
        run: uv run --frozen ruff check ${{ env.PROJECT_PATH }}/

      - name: Check if requirements.txt is up-to-date (needed for OpenSSF scorecard)
        run: |
          uv pip compile pyproject.toml --generate-hashes --output-file /tmp/requirements.txt --custom-compile-command "uv pip compile pyproject.toml --generate-hashes --output-file requirements.txt"
          diff -u requirements.txt /tmp/requirements.txt

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      # https://github.com/actions/checkout
      - name: ⤵️ Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      # https://github.com/astral-sh/setup-uv
      - name: 🏗 Install uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff # v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          cache-local-path: ${{ env.UV_CACHE_DIR }}
          python-version: ${{ matrix.python-version }}

      - name: install openldap dependencies
        run: sudo apt-get install -y libldap2-dev libsasl2-dev

      - name: 🏗 Install the project
        run: uv sync --locked --dev --all-extras

      - name: Run pytest
        run: uv run --frozen pytest tests/ --cov=./ --cov-report=xml --junitxml=pytest-report.xml

      # https://github.com/actions/upload-artifact
      - name: Upload test report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: pytest-report-${{ matrix.python-version }}
          path: pytest-report.xml

      # https://github.com/actions/upload-artifact
      - name: Upload coverage results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-results-${{ matrix.python-version }}
          path: coverage.xml

      # # https://github.com/codecov/codecov-action
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@04b047e8bb82a0c002c8312c1c880fbc6a999d45 # v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     fail_ci_if_error: true
